---
- name: Update Timezone to Etc/UTC
  copy: content="Etc/UTC\n" dest=/etc/timezone owner=root group=root mode=0644
  register: timezone

- name: Reconfigure Timezone Data
  command: dpkg-reconfigure -f noninteractive tzdata
  when: timezone.changed