---
- name: Update apt packages
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  tags:
    - packages
  when: ansible_os_family == 'Debian'

- name: Upgrade apt packages
  ansible.builtin.apt:
    upgrade: dist
    force_apt_get: yes
  tags:
    - packages
  when: ansible_os_family == 'Debian'

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  tags:
    - packages
    - reboot_required
  when: ansible_os_family == 'Debian'

- name: Reboot the server
  ansible.builtin.reboot:
  tags:
    - packages
    - reboot_required
  when: ansible_os_family == 'Debian' and reboot_required_file.stat.exists == true and reboot_allowed is defined

- name: Print reboot required message
  ansible.builtin.debug:
    msg: "Reboot is required but not allowed"
  tags:
    - packages
    - reboot_required
  when: ansible_os_family == 'Debian' and reboot_required_file.stat.exists == true and reboot_allowed is not defined