---
- hosts: all
  become: true

  tasks:
    - name: Update apt packages
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
      tags:
        - packages
      when: ansible_os_family == 'Debian'

    - name: Upgrade apt packages
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: yes
      tags:
        - packages
      when: ansible_os_family == 'Debian'

    - name: Install base packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ install_packages }}"
      tags:
        - packages
      when: ansible_os_family == 'Debian'

    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      tags:
        - packages
        - reboot_required
      when: ansible_os_family == 'Debian'

    - name: Reboot the server
      reboot:
      when: ansible_os_family == 'Debian' and reboot_required_file.stat.exists == true and skip_reboot is not defined and skip_reboot == false
      tags:
        - packages
        - reboot_required