---
# install smallstep ca when specified version is not installed
- name: install smallstep ca
  apt:
    deb: "{{ smallstep_cli_deb }}"
  tags: internal-ca

- name: Install internal Root CA Certificate
  shell:
    cmd: "step ca bootstrap --ca-url {{ smallstep_pki_url }} --fingerprint {{ smallstep_pki_fingerprint }} --install -f" 
    creates: "$(step path) /certs/root_ca.crt"
  tags: internal-ca
