---
- name: Update apt packages
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  tags:
    - packages
  when: ansible_os_family == 'Debian'

- name: Install base packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ install_packages }}"
  tags:
    - packages
  when: ansible_os_family == 'Debian'